# Generated by Django 3.1.1 on 2020-09-11 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=10)),
                ('white', models.CharField(default='', max_length=20)),
                ('black', models.CharField(default='', max_length=20)),
                ('board', models.CharField(default='Board()', max_length=40)),
                ('moves', models.CharField(default='[]', max_length=3000)),
            ],
        ),
    ]
