# Generated by Django 3.1.6 on 2021-02-17 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chessapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='in progress', max_length=100)),
                ('name', models.CharField(default='', max_length=10)),
                ('white', models.CharField(default='', max_length=30)),
                ('black', models.CharField(default='', max_length=30)),
                ('board', models.CharField(default='Board()', max_length=100)),
                ('moves', models.CharField(default='[]', max_length=10000)),
            ],
        ),
    ]
