# Generated by Django 3.1.6 on 2021-02-17 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chessapp', '0002_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='moves',
            field=models.CharField(default='[]', max_length=10000),
        ),
    ]
